# CI values for chart-neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


rules:
  admission:
    mode: "monitor" # one of: monitor, protect
    customRules:
      - action: allow
        comment: Allow monitoring app to modify deployments anywhere
        criteria:
          - name: user
            op: containsAny
            value: system:serviceaccount:monitoring:my-app-service-account
  response:
    policies:
      - '{"insert":{"after":0,"rules":[{"group":null,"conditions":[{"type":"name","value":"Admission.Control.Denied"}],"actions":["webhook"],"event":"admission-control","disable":false}]}}'
      - '{"insert":{"after":1,"rules":[{"group":null,"conditions":[],"actions":["webhook"],"event":"security-event","disable":true}]}}'
      - '{"insert":{"after":2,"rules":[{"group":null,"conditions":[{"type":"level","value":"Error"}],"actions":["webhook"],"event":"security-event","disable":true}]}}'
      - '{"insert":{"after":3,"rules":[{"group":null,"conditions":[{"type":"name","value":"Container.Privilege.Escalation"}],"actions":["quarantine"],"event":"security-event","disable":true}]}}'
      - '{"insert":{"after":4,"rules":[{"group":null,"conditions":[{"type":"cve-high","value":"10"}],"actions":["quarantine"],"event":"cve-report","disable":true}]}}'
      - '{"insert":{"after":5,"rules":[{"group":null,"conditions":[{"type":"name","value":"Container.Quarantined"}],"actions":["webhook"],"event":"event","disable":false}]}}'
      - '{"insert":{"after":6,"rules":[{"group":null,"conditions":[{"type":"name","value":"5.4"}],"actions":["webhook"],"event":"compliance","disable":true}]}}'
config:
  sleep: 10 # we dont use backup in ci, we don't need long sleep

keyVaults:
  cftneuvector:
    secrets:
      - neuvector-admin-password
      - neuvector-license-dev
      - neuvector-slack-webhook
      - neuvector-new-admin-password
global:
  enableKeyVaults: true
  tenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
  environment: sbox

keyvault:
  name: cftneuvector
  licensesecretname: neuvector-license-dev

neuvector:
  cve:
    scanner:
      image:
        repository: imported/neuvector/scanner
