# Default values for chart-neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

useWorkloadIdentity: true

rules:
  admission:
    enable: false
    mode: "monitor"  # one of: monitor, protect
    rules: []
    defaultAction: "allow"
    admClientMode: "service"
    service: "neuvector"
  response:
    policies: []
  network: []

groups: []

config:
  autoScan: true
  sleep: 180
  forceLicenseUpdate: false

neuvector:
  registry: hmctspublic.azurecr.io
  crdwebhook:
    enabled: false

  containerd:
    enabled: true

  manager:
    image:
      repository: imported/neuvector/manager
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - neuvector-manager-pod
              topologyKey: "kubernetes.io/hostname"
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.azure.com/mode
                  operator: In
                  values:
                    - system
    svc:
      type: ClusterIP
    env:
      ssl: true
  cve:
    scanner:
      image:
        repository: imported/neuvector/scanner
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - neuvector-scanner-pod
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: In
                    values:
                      - system
  controller:
    image:
      repository: imported/neuvector/controller
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - neuvector-controller-pod
              topologyKey: "kubernetes.io/hostname"
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: kubernetes.azure.com/mode
                  operator: In
                  values:
                    - system
    ingress:
      enabled: true
      host: neuvector.hmcts.com
      path: "/api"
    apisvc:
      type: ClusterIP

  enforcer:
    image:
      repository: imported/neuvector/enforcer
  updater:
    image:
      repository: imported/neuvector/updater

global:
  enableKeyVaults: true
  tenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082

keyvault:
  licensesecretname: neuvector-license-dev
