# Default values for chart-neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

keyvault:
  aadpodidbinding: neuvector
  name: cftapps-sbox
  resourcegroup: core-infra-sbox-rg
  subscriptionid: b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb
  tenantid: 531ff96d-0ae9-462a-8d2d-bec7c0b42082
  licensesecretname: neuvector-license-dev

rules:
  admission:
    enable: false
    mode: "monitor"  # one of: monitor, protect
    rules: []
    defaultAction: "allow"
    admClientMode: "service"
    service: "neuvector"
  response:
    policies: []
  network: []

groups: []

config:
  autoScan: true
  sleep: 180

neuvector:
  registry: hmctsprivate.azurecr.io
  tag: 4.0.1

  containerd:
    enabled: true

  manager:
    svc:
      type: ClusterIP
    env:
      ssl: false

  controller:
    ingress:
      enabled: true
      host: neuvector.hmcts.com
      path: "/api"
    apisvc:
      type: ClusterIP

