# Default values for chart-neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


rules:
  admission:
    enable: false
    mode: "monitor"  # one of: monitor, protect
    rules: []
    defaultAction: "allow"
    admClientMode: "service"
    service: "neuvector"
  response:
    policies: []
  network: []

groups: []

config:
  autoScan: true
  sleep: 180

neuvector:
  registry: hmctsprivate.azurecr.io
  tag: 4.0.1

  containerd:
    enabled: true

  manager:
    svc:
      type: ClusterIP
    env:
      ssl: false

  controller:
    ingress:
      enabled: true
      host: neuvector.hmcts.com
      path: "/api"
    apisvc:
      type: ClusterIP

keyVaults:
  cftapps-sbox:
    secrets:
      - neuvector-admin-password  
      - neuvector-license-dev
      - neuvector-slack-webhook
      - neuvector-new-admin-password
global:
  enableKeyVaults: true 
  tenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082


keyvault: 
  name: cftapps-sbox
  licensesecretname: neuvector-license-dev