# Default values for chart-neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


rules:
  admission:
    enable: false
    mode: "monitor"  # one of: monitor, protect
    rules: []
    defaultAction: "allow"
    admClientMode: "service"
    service: "neuvector"
  response:
    policies: []
  network: []

groups: []

config:
  autoScan: true
  sleep: 180

neuvector:
  registry: hmctsprivate.azurecr.io
  tag: 4.1.2

  containerd:
    enabled: true

  manager:
    svc:
      type: ClusterIP
    env:
      ssl: true

  controller:
    ingress:
      enabled: true
      host: neuvector.hmcts.com
      path: "/api"
    apisvc:
      type: ClusterIP

global:
  enableKeyVaults: true
  tenantId: 531ff96d-0ae9-462a-8d2d-bec7c0b42082

keyvault:
  licensesecretname: neuvector-license-dev
  aadpodidbinding: neuvector
