{{- $customRules := .Values.rules.admission.customRules | default (list) -}}
{{- $defaultRules := .Values.rules.admission.defaultRules | default (list) -}}
{{- $rules := concat $customRules $defaultRules -}}
---
apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
  labels:
    chart: {{ template "chart-neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  config:
    client_mode: {{ .Values.rules.admission.admClientMode }}
    enable: {{ .Values.rules.admission.enable }}
    mode: {{ .Values.rules.admission.mode }}
{{- if $rules }}
  rules:
{{ toYaml $rules | indent 2 }}
{{- else }}
  rules: []
{{- end }}
