{{ if .Values.rules.admission.enable }}
apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  config:
    client_mode: service
    enable: true
    mode: {{ .Values.rules.admission.mode }}
  rules:
  - action: allow
    comment: Allow admin namespaces
    criteria:
    - name: namespace
      op: containsAny
      value: knode-system,monitoring,flux-system,dynatrace,azureserviceoperator-system,cert-manager,keda,admin,kured,artifactory,pact-broker
  - action: allow
    comment: Allow HMCTS registries
    criteria:
    - name: imageRegistry
      op: containsAny
      value: https://hmctsprod.azurecr.io,https://hmctssbox.azurecr.io/,https://hmctspublic.azurecr.io/,https://hmctsprivate.azurecr.io/,https://sdshmctspublic.azurecr.io/
    comment: Default deny
    criteria:
    - name: imageRegistry
      op: containsAny
      value: https://localhost/,https://*.*/
{{ end }}
