{{- if .Values.rules.admission.enable }}
{{- $customRules := .Values.rules.admission.customRules | default (list) -}}
{{- $defaultRules := .Values.rules.admission.defaultRules | default (list) -}}
{{- $rules := concat $customRules $defaultRules -}}
apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  config:
    client_mode: {{ .Values.rules.admission.admClientMode }}
    enable: true
    mode: {{ .Values.rules.admission.mode }}
{{- if $rules }}
  rules:
{{ toYaml $rules | indent 2 }}
{{- else }}
  rules: []
{{- end }}
{{- end }}
