{{- $customGroups := .Values.groups.customGroups | default (list) -}}
{{- $defaultGroups := .Values.groups.defaultGroups | default (list) -}}
{{- $groups := concat $customGroups $defaultGroups -}}
{{- range $group := $groups }}
---
apiVersion: neuvector.com/v1
kind: NvGroupDefinition
metadata:
  name: {{ $group.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    chart: {{ template "chart-neuvector.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  selector:
    name: {{ $group.name }}
    criteria:
      {{- toYaml $group.criteria | nindent 6 }}
{{- end }}
