{{- range .Values.groups }}
---
apiVersion: neuvector.com/v1
kind: NvGroupDefinition
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    chart: {{ template "chart-neuvector.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  selector:
    name: {{ .name }}
    criteria:
      {{- toYaml .criteria | nindent 6 }}
{{- end }}
