---
# relies on httptohttpsredirect middleware existing in admin namespace. definied in cnp-flux-config
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neuvector-redirect-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: admin-httptohttpsredirect@kubernetescrd
spec:
  rules:
    - host: {{ .Values.manager.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: neuvector-service-webui
                port:
                  number: 8443
            path: /
            pathType: ImplementationSpecific