{{- $groups := .Values.groups | default (list) -}}
{{- $customRules := .Values.rules.network.customRules | default (list) -}}
{{- $defaultRules := .Values.rules.network.defaultRules | default (list) -}}
{{- $items := concat $groups (concat $customRules $defaultRules) -}}
{{- if $items }}
apiVersion: v1
items:
{{ toYaml $items | indent 0 }}
kind: List
metadata: null
{{- end }}
