{{- if .Values.keyVaults -}}
apiVersion: batch/v1
kind: Job
metadata:
  # we don't include neuvector in the pod name because then neuvector blocks anything 'unexpected'
  name: restapi-config-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "chart-neuvector.name" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation # preserve job pod but delete before next install/upgrade
spec:
  template:
    metadata:
      name: {{ template "chart-neuvector.fullname" . }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ template "chart-neuvector.name" . }}
        aadpodidbinding: {{ .Values.keyvault.aadpodidbinding }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: post-install-job
          image: hmctspublic.azurecr.io/docker-curl
          command: ["/bin/sh", "-c", "/etc/config/config.sh"]
          {{- ( include "hmcts.secretMounts.v1" . ) | indent 10   }}
            - name: config-volume
              mountPath: /etc/config

      {{- ( include "hmcts.secretCSIVolumes.v1" . ) | indent 6 }}
        - name: config-volume
          configMap:
            name: neuvector-restapi-config
            defaultMode: 0755
{{- end -}}
