apiVersion: v1
kind: ConfigMap
metadata:
  name: neuvector-restapi-config
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "chart-neuvector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.sh: |
    #!/bin/sh

    # NV API URL. Note just using hostname doesn't always resolve...
    API_URL="https://neuvector-svc-controller.neuvector.svc.cluster.local:10443/v1"

    # KV Flexvol secrets
    NV_ADMIN_PASSWORD=$(cat /kvmnt/neuvector-admin-password)
    NV_NEW_ADMIN_PASSWORD=$(cat /kvmnt/neuvector-new-admin-password)
    NV_LICENSE=$(cat /kvmnt/{{ .Values.keyvault.licensececretname }})
    NV_SLACK_WEBHOOK=$(cat /kvmnt/neuvector-slack-webhook)

    # TODO: Some logic to handle the case where the new admin password has already been set...
    echo "Getting authentication token..."
    TOKEN=$(curl -sk -H "Content-Type: application/json" -d '{"password": {"username": "admin", "password": "'"$NV_ADMIN_PASSWORD"'"}}' "$API_URL/auth" | jq -r .token.token)

    echo "Accepting EULA..."
    curl -sk -H "Content-Type: application/json" -H "X-Auth-Token: $TOKEN" -d '{"eula":{"accepted":true}}' $API_URL/eula

    echo "Setting license..."
    curl -sk -H "Content-Type: application/json" -H "X-Auth-Token: $TOKEN" -d '{"license_key": "'"$NV_LICENSE"'"}' $API_URL/system/license/update

    echo "Changing default admin password..."
    curl -sk -H "Content-Type: application/json" -H "X-Auth-Token: $TOKEN" $API_URL/user/admin -X PATCH -d '{"config":{"fullname":"admin","password":"'"$NV_ADMIN_PASSWORD"'","new_password":"'"$NV_NEW_ADMIN_PASSWORD"'"}}'

    # Set the Slack webhook URL
    curl -sk -H "Content-Type: application/json" -H "X-Auth-Token: $TOKEN" $API_URL/system/config -X PATCH -d '{"config":{"webhook_status":true,"webhook_url":"'"$NV_SLACK_WEBHOOK"'"}}'
